language: c
env:
  global:
    - secure: h2PBHrsRa94qrWZYSs+B0kwzeVw7uFFyaZ/0hDIxBd+GRHi5WgyjGL+5ZJMnFayahvqwoiaJYWzs2gI5pxCvTGpdUlfZFZmazjZtUMXViyRd1OhEGVk/oG8KRALcbyfBAIMpPeddvS/4H5e5QkMlr+8QCMSn28IjftjZlngQ8V4=

install:
  - bash ./.travis.deps.sh

script:
  - bash ./.travis.build.sh

after_script:
  - bash ./.travis.after.sh
