language: c
env:
  global:
    - secure: h2PBHrsRa94qrWZYSs+B0kwzeVw7uFFyaZ/0hDIxBd+GRHi5WgyjGL+5ZJMnFayahvqwoiaJYWzs2gI5pxCvTGpdUlfZFZmazjZtUMXViyRd1OhEGVk/oG8KRALcbyfBAIMpPeddvS/4H5e5QkMlr+8QCMSn28IjftjZlngQ8V4=
before_install:
  - sudo add-apt-repository -y ppa:hansjorg/rust
  - sudo apt-get update -qq
install:
  - sudo apt-get install rust-nightly
  - sudo apt-get install libudev-dev libusb-1.0-0-dev
  - sudo apt-get install autotools-dev autoconf automake libtool
  - curl -L -O https://github.com/signal11/hidapi/archive/hidapi-0.8.0-rc1.tar.gz
  - tar xfz hidapi-0.8.0-rc1.tar.gz
  - (cd hidapi-hidapi-0.8.0-rc1 && ./bootstrap && ./configure && make && sudo make install)
  - ls -l /usr/local/lib
  - git clone --depth 1 --recursive https://github.com/rust-lang/cargo
  - (cd cargo && make && sudo make install)

script:
  - export LIBRARY_PATH=/usr/local/lib:$LIBRARY_PATH
  - rustc --version
  - cargo build
  - rustdoc -o doc src/hidapi/lib.rs

after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
