language: c
env:
  global:
    - secure: tuG6DoMSYruOZyGCSLuWAJtRi9JG4ZwSPPLSwgmCMSt+k2sTBM6IoG+Xm8BgeCGx6f2V/KyoFh+RGRk7897u4hKQ6xYjxJXQkRg036d5qfk6jzAF1H0/bmM9ZDpaqBOYYjNDfQzbn8ivaso653mkSfDF3K5loulddPggEyfr6NU=

install:
  - bash ./.travis.deps.sh

script:
  - bash ./.travis.build.sh

after_script:
  - bash ./.travis.after.sh
